version: '2'
services:
    ghostos:
      image: ghost
      restart: always
      depends_on:
        - main_ghost_database
      ports:
        - 2368:2368
      volumes:
        - gh_storage_new:/var/lib/ghost
      environment:
        database_client: mysql
        database_connection_host: main_ghost_database
        database_connection_user: sachin
        database_connection_password: redhat
        database_connection_database: main_docker_database
        
    ghostdatabase:main_ghost_database:
                      image: mysql
                      volumes:
                        - db_storage_new:/var/lib/mysql
                      restart: always
                      environment:
                        MYSQL_ROOT_PASSWORD: redhat
                        MYSQL_USER: sachin
                        MYSQL_PASSWORD: redhat
                        MYSQL_DATABASE: main_docker_database
volumes:
  main_database:
  main_ghost_storage:

